export enum BtnDesign {
  signIn = 'signIn',
  signUp = 'signUp',
  logOut = 'logOut',
  createArticle = 'createArticle',
  createNewArticle = 'createNewArticle',
  delete = 'delete',
  deleteArticle = 'deleteArticle',
  edit = 'edit',
  addTag = 'addTag',
  goBackToHomepage = 'goBackToHomepage',
  create = 'create',
  login = 'login',
  save = 'save',
  send = 'send',
}
